### ISSUE TITLE
Suggestion: Fan Mades

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#725] opened 2021-11-05 01:37 UTC
Fans can make Fan Made games inspired in a Game that you launched, demand Fan Mades Games or just leave to them make what they want

**Comment by xsellier** [comment] 2021-11-05 07:45
Kind of duplicate of: https://github.com/binogure-studio/city-game-studio-i18n/issues/238
This needs to be ellaorated, a single sentence isn't a new feature by itself. There is a template for suggestion please use it.

**Closed as completed by xsellier** 2021-11-05 07:45 UTC
Labels: Duplicate
