### ISSUE TITLE
Freezing And Unfreezing

### ISSUE THREAD

**Issue by GeneralNW** [binogure-studio/city-game-studio-i18n#125] opened 2019-03-12 06:08 UTC
Hello.
When I was waiting for my game to be complete the game would freeze and unfreeze every 2-3 minutes and it will stay frozen this for about 30 seconds and unfreeze. Then it would freeze and unfreeze every 10-15 seconds and unfreeze 2 seconds after which got annoying after a while. I couldn't get a screenshot because it started only doing the 2 second freezes. I will update this post if I get a screenshot.
Hope it all makes sense!

**Comment by GeneralNW** [comment] 2019-03-12 06:16
Hey here's a screen shot of what happened and it didn't respond for a while.
https://user-images.githubusercontent.com/48432141/54178567-2b925080-44fb-11e9-958d-6817b7a4a538.PNG

**Comment by GeneralNW** [comment] 2019-03-12 06:47
Also just a question are you going to be able to make your own console in the future?

**Comment by xsellier** [comment] 2019-03-12 13:37
Hey,

I'm sorry you are having such a terrible experience with the game.
I want to help you improving that.

- Please, may you open the game, load a game, and then send me a bug report (I will check your savegame)
- Update your graphic drivers to the latest version:
  - AMD: https://www.amd.com/en/support
  - NVidia: https://www.nvidia.com/download/index.aspx
  - Intel: https://downloadcenter.intel.com/product/80939/Graphics-Drivers
- Start the `CityGameStudio64.bat` from this folder `C:/Program Files (x86)/Steam/steamapps/common/City Game Studio/`
- After a while, please attach the CityGameStudio.log from the same folder to this ticket please.
- Do you use an anti virus (if so, which one)

**Comment by GeneralNW** [comment] 2019-03-12 19:05
Ok I will do all that when I have some spare time thanks!

**Comment by GeneralNW** [comment] 2019-03-13 06:30
I have sent a bug report on the game as the issue is still happening also I use malware bytes

**Comment by xsellier** [comment] 2019-03-13 13:01
I've got your savegame, and Im able to reproduce the freeze you are talking about. So it seems to be related to your savegame, but I think I can fix it (from the game itself)

**Comment by GeneralNW** [comment] 2019-03-13 18:36
Ok awesome!

**Comment by GeneralNW** [comment] 2019-03-15 08:48
Hey just letting you know I sent another bug report and I hope that I can help you improve the game!

**Comment by xsellier** [comment] 2019-03-16 18:46
Its been fixed. I close it

**Closed as completed by xsellier** 2019-03-16 18:46 UTC
Labels: Bug
