### ISSUE TITLE
Suggestion: Make the world and the audience more alive and snappy

### ISSUE THREAD

**Issue by Strompper** [binogure-studio/city-game-studio-i18n#404] opened 2020-03-19 21:09 UTC
I would see this game as stellar if there would be reactions from media and fans and even from the staff regarding your choices with the studio, like pop-up messages and maybe even a special chart to see what is the view from the outside. Imagine lying with hyping the game or straight up cancelling it (without being able to give out a reason, for now) almost at the end of dev. cycle. You can do that right now, but there isn't really something satisfying about doing certain things or giving second thoughts to small decisions if there isn't really an audience to elate or disappoint.

**Comment by xsellier** [comment] 2020-03-20 13:51
Hello @Strompper and thank you for this great suggestion.
I want to add feedbacks from the community, I mean when you publish a game you will receive a letter from your fans asking for new things. This suggestions has already been described by @Tesba in this ticket: https://github.com/binogure-studio/city-game-studio-i18n/issues/96
But I also want to add feedback from your development team, and this has also already been described by this ticket: https://github.com/binogure-studio/city-game-studio-i18n/issues/263

It is planned, and I will implement it, but I need to stick to the [current roadmap](https://github.com/binogure-studio/city-game-studio-i18n/projects/1).
I hope you don't mind because Im gonna close this ticket because it is a duplicate of the other 2 tickets.

**Closed as completed** 2020-03-20 13:52 UTC
Labels: Duplicate, enhancement
