### ISSUE TITLE
Trade IP

### ISSUE THREAD

**Issue by IkhwanKS3** [binogure-studio/city-game-studio-i18n#361] opened 2020-01-24 02:53 UTC
You can buy and sell IP with other companies. The price of the IP will be based on how successful and the score the IP received in the past 4 years. You will also get a bonus hype if the IP is successful before but get a bad reputation if you cannot deliver enough quality to compete with the use of the IP before.

**Comment by xsellier** [comment] 2020-02-13 00:08
Duplicate of:
https://github.com/binogure-studio/city-game-studio-i18n/issues/78

**Closed as completed by xsellier** 2020-02-13 00:08 UTC
Labels: Duplicate
