### ISSUE TITLE
Suggestion: Automark for store

### ISSUE THREAD

**Issue by FolioNov9m** [binogure-studio/city-game-studio-i18n#630] opened 2021-06-26 10:01 UTC
This:

![image](https://user-images.githubusercontent.com/80094976/123509507-993bf980-d67e-11eb-9508-46796c064bc8.png)

Sometimes just forgot to check mark, so mb make this automatically for able platforms?

**Comment by xsellier** [comment] 2021-06-30 08:10
Implemented, should be available later today, thank you for that tip!

**Comment by FolioNov9m** [comment] 2021-06-30 08:13
> Implemented, should be available later today, thank you for that tip!

thank you for this fix! ;)

**Comment by FolioNov9m** [comment] 2021-06-30 17:25
Looks like after update mark is auto set, but store is empty still :(

I send you bug report into game

**Comment by FolioNov9m** [comment] 2021-06-30 17:26
Update sorry, it looks like rating is broken

![image](https://user-images.githubusercontent.com/80094976/124005166-70e72e80-d9e1-11eb-998f-7961fa258e69.png)

![image](https://user-images.githubusercontent.com/80094976/124005196-78a6d300-d9e1-11eb-8585-b19716f126c8.png)

**Comment by FolioNov9m** [comment] 2021-06-30 17:27
And no profits

![image](https://user-images.githubusercontent.com/80094976/124005293-907e5700-d9e1-11eb-8bd4-ee840dddb66b.png)

**Comment by FolioNov9m** [comment] 2021-06-30 17:29
Games in Store have negative fanbase reaction xD

![image](https://user-images.githubusercontent.com/80094976/124005576-ec48e000-d9e1-11eb-8d8e-40548ecb4f42.png)

**Comment by xsellier** [comment] 2021-06-30 17:52
This ticket contains too many differnt topics. I have to lock it.

Regarding the fanbase, it is not a bug, you can lose fans, that's normal.
Regarding profits, I'm gonna have a look at it.

**Comment by xsellier** [comment] 2021-07-01 10:11
Thank you for the report.

I'm now unlocking this ticket since the feature has been implemented and reported bugs fixed with rc21.

**Closed as completed** 2021-10-12 16:30 UTC
Labels: enhancement, Done
