### ISSUE TITLE
Subscription Services 

### ISSUE THREAD

**Issue by SickoonSeriesX** [binogure-studio/city-game-studio-i18n#816] opened 2022-07-16 16:35 UTC
Subscription services as we know now the becoming the future of gaming industry I think we need this is CGS 

So we can add subscription services in 2006- or 2007 in game time we can have feature  for subscription services similar to the dematerialised Store and if we add a subscription to our own platform then we can make paid online multiplayer we can add other competitors game on our Service from contract and add our own game to the service on day one even this will attract more people towards the game. And we could also make a cloud gaming platform . 

We should have a UI to see the live number of subscribers to our service 

Also adding mod support similar to dematerialised store to subscription service would be nice thing to us , modders 

Sincerely Sicko

**Comment by xsellier** [comment] 2022-07-16 17:08
Thanks for the suggestion, however it is a duplicate of:
https://github.com/binogure-studio/city-game-studio-i18n/issues/531

Closing but linking for more context.

**Closed as completed by xsellier** 2022-07-16 17:08 UTC
Labels: Duplicate
