### ISSUE TITLE
Suggestion: Rename and expand exhibition center

### ISSUE THREAD

**Issue by Opsonic** [binogure-studio/city-game-studio-i18n#190] opened 2019-04-22 15:42 UTC
A few things regarding exhibition centers; after building an exhibition center there is no way to rename the building (I accidentally forgot to name one of mine and now it is just called "building", which just annoys me) or upgrade it, instead you have to build a whole new tower if you want to increase its size. Also, it would be cool if expanding/building took time to finish, rather than being instantaneous.

**Comment by xsellier** [comment] 2019-10-19 13:54
Since v0.25.0 you can rename the convention center. However you cannot expand it yet.

**Comment by xsellier** [comment] 2020-08-15 12:20
Expansion is now a duplicate of https://github.com/binogure-studio/city-game-studio-i18n/issues/305

**Closed as completed by xsellier** 2020-08-15 12:20 UTC
Labels: enhancement
