### ISSUE TITLE
Discussion: Customized game creation

### ISSUE THREAD

**Issue by WayneFTWGitHUB** [binogure-studio/city-game-studio-i18n#270] opened 2019-09-25 11:48 UTC
This game is really good. But. I feel like Game Dev Tycoon lets you be more creative when making a game. In GDT you can make your own game engine and choose if you want the game to be open world, celebrity voice acting and stuffs like that. You can also make your own gaming console. Cuz' now when you have finished the game there isn't that much to do.

**Comment by xsellier** [comment] 2019-09-25 14:13
Those features (https://github.com/binogure-studio/city-game-studio-i18n/issues/261 and https://github.com/binogure-studio/city-game-studio-i18n/projects/1#card-16510914), once implemented should help like a lot. However I also want the game to be a management game, not only a game maker simulator. 

For sure, you should be able to customize your game, when you are creating it. But you also need to focus on your studio, your competitors, the marketing, your employees healthiness... 

However if you have any other ideas, other than ideas already suggested, please tell me.

**Comment by xsellier** [comment] 2019-12-07 17:54
Duplicate of:
https://github.com/binogure-studio/city-game-studio-i18n/issues/260

**Closed as completed by xsellier** 2019-12-07 17:54 UTC
Labels: Duplicate, Question
