### ISSUE TITLE
Suggestion: New Marketing Campaigns

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#726] opened 2021-11-05 01:44 UTC
Can make movies about games, it can be just like the Marketing Campaigns or it can be like the Create Game system, i think it can be like making remakes
Requirements: 100.000 dollars (depend in the duration of the movie) 1 Hour: 100.000, 1 Hour 30 Minutes: 250.000, 2 Hours: 500.000, also can boost the quality of the movie hiring  Expert Cameramans, An Expert Screenwriter etc etc, the other way of adding this is just like Television Marketings Campaigns

**Comment by xsellier** [comment] 2021-11-05 07:42
Duplicate of https://github.com/binogure-studio/city-game-studio-i18n/issues/329

**Closed as completed by xsellier** 2021-11-05 07:42 UTC
Labels: Duplicate
