### ISSUE TITLE
Bug: Number of online game players

### ISSUE THREAD

**Issue by Th-byte** [binogure-studio/city-game-studio-i18n#383] opened 2020-02-20 05:44 UTC
There is no good solution to the problems existing in online games. The problems still exist. The players of online games cannot keep growing. Although the quality of the game is very good and the marketing methods are very good, the number of online players can not keep growing, which is less one time after another

**Comment by xsellier** [comment] 2020-02-20 13:38
Closing due to duplicate of https://github.com/binogure-studio/city-game-studio-i18n/issues/382

**Closed as completed by xsellier** 2020-02-20 13:38 UTC
Labels: Duplicate
