### ISSUE TITLE
Suggestion: Add buttons for Discounts

### ISSUE THREAD

**Issue by weaktt** [binogure-studio/city-game-studio-i18n#890] opened 2024-07-01 18:22 UTC
Add few buttons when you are trying to make game discounts:
max = 95%
half  = 50%
mb some others like 10-25%
and for time add "Do Forever" button

**Comment by VeteranXT** [comment] 2024-09-28 23:07
Would like to add: Add events and Seasoned Discounts. Like every Decembar at X price.

**Comment by xsellier** [comment] 2024-10-09 11:34
Added a max and min tot he game. It should be part of the next update (or the unstable branch later today).

**Comment by xsellier** [comment] 2024-10-09 11:35
This one is a duplicate of this ticket, I'm closing it in favor of:
https://github.com/binogure-studio/city-game-studio-i18n/issues/896

**Closed as completed by xsellier** 2024-10-09 11:35 UTC
Labels: Suggestion
