### ISSUE TITLE
Suggestion: The option to have competitors you've bought out, remain autonomous

### ISSUE THREAD

**Issue by proxyspride** [binogure-studio/city-game-studio-i18n#535] opened 2021-02-07 10:24 UTC
**Is your feature request related to a problem? Please describe.**
Yes, every time I buy out a competitor I have to worry about new buildings and employees that I have no idea what to do with, have no need for, and would rather just not have to worry about. I still want to buy out my competitors because I don't want them taking market strength, but it's not enjoyable at all and is very time-consuming to sit and figure out who should go where, and what building should now do what.

**Describe the solution you'd like**
The option to have competitors you've bought out, remain autonomous. This meaning that they continue to do exactly as they were doing before you bought their company. They would continue to make random games, only now _you_ would make the profits, and the costs would come out of _your_ pocket, and wouldn't have to worry about insane amounts of new employees and buildings, and moving people around or whatever, if you don't want to.

**Describe alternatives you've considered**
I'm not sure of an alternative, but I would take one!

**Additional context**
If the newly bought company is chosen to remain autonomous: the option to still have their offices available for use, if they aren't already busy with an autonomous task, of course.

**Comment by xsellier** [comment] 2021-02-07 10:24
Duplicate of:
https://github.com/binogure-studio/city-game-studio-i18n/issues/409

**Closed as completed by xsellier** 2021-02-07 10:24 UTC
