### ISSUE TITLE
Suggestion: subsidiaries?

### ISSUE THREAD

**Issue by Malaras** [binogure-studio/city-game-studio-i18n#85] opened 2019-03-01 08:39 UTC
Hello, Could this be a feature?
Create small subsidiary  250-500k or what not.
Medium
Large etc etc
Then have them create combo of themes/genres or stick to certain ones?or consoles
Your subsidiary will have funds, you have the option to add and remove funds from them. Also can set how many people work at this particular office(s).

Just wanted to throw the idea out there before i get to far into it to see if you like the idea.

Thanks.

**Comment by xsellier** [comment] 2019-03-01 13:53
Hey @Malaras ,

Thank you for that suggestion!
A new employee is planned, it is a producer. A producer will let a studio auto-manage itself, so it will act like a subsidiary. So you will be able to turn your own studio into subsidiary.

**Comment by Spartuluz** [comment] 2020-10-21 15:09
Spartuluz commented now
I think it's interesting this idea, because for me who's playing, I already have about 5 subsidies, and it becomes a lot to control at the same time, imagine more. So it would be good for them to manage themselves.

**Comment by xsellier** [comment] 2021-09-05 08:26
Duplicate of this ticket:
https://github.com/binogure-studio/city-game-studio-i18n/issues/409

**Closed as completed by xsellier** 2021-09-05 08:26 UTC
Labels: enhancement
