### ISSUE TITLE
F2P Game/Online Store

### ISSUE THREAD

**Issue by GeneralNW** [binogure-studio/city-game-studio-i18n#121] opened 2019-03-11 08:12 UTC
Hey guys great job so far.
My suggestion Is to add a feature for the game that lets you make a free to play game on the servers with in-app purchases. Also would be cool to Have your own online store such as steam and you can set the price for other developers to put their games up on the store with a higher price set gets less games on the store but higher quality but if you put the price down more games will go on the store but the quality of those games will be lower.
I hope my suggestion makes sense.
Keep up the good work guys!

**Comment by xsellier** [comment] 2019-03-11 16:19
On the roadmap already:
https://github.com/binogure-studio/city-game-studio-i18n/projects/1#card-16510914

Duplicate of:
https://github.com/binogure-studio/city-game-studio-i18n/issues/227

**Closed as completed** 2019-07-01 22:30 UTC
Labels: Duplicate, enhancement
