### ISSUE TITLE
Backwards compatible consoles/Updating consoles

### ISSUE THREAD

**Issue by Zebbidoo** [binogure-studio/city-game-studio-i18n#673] opened 2021-09-08 07:42 UTC
**Is your feature request related to a problem? Please describe.**
I would really like to be able to make my consoles backwards compatible with games from it's predecessor, a la Game Boy Advance or Playstation 2.
I'm also often frustrated when I want to make small changes to a console and have to develop it from scratch again. I would like to be able to make something like a Ps4 Pro, or Ps2 Slim etc. ie a slightly improved version of a console.

**Describe the solution you'd like**
It would be really cool if when developing a console, you could add a way for games from a previous console to be compatible with your new console. Perhaps the development of this will cost more the older the predecessor is.

Also It would be great if a new console could be created that plays the same games. Such as making a new version of the same console. Development would be easier depending on how many old components are kept.

**Describe alternatives you've considered**
An alternate solution I thought of is to make all console development cheaper/faster when you reuse components from a previous console. Basically just a discount in time and cost for each reused component. This makes sense from a logical and gameplay perspective and I feel like it would add some flavour while not adding that much complexity.

**Additional context**

**Comment by xsellier** [comment] 2021-09-16 07:19
Duplicate of:
https://github.com/binogure-studio/city-game-studio-i18n/issues/659

**Closed as completed by xsellier** 2021-09-16 07:19 UTC
Labels: Duplicate
