### ISSUE TITLE
Suggestion: IPs / Franchises / Brand system

### ISSUE THREAD

**Issue by LuisBravoC** [binogure-studio/city-game-studio-i18n#869] opened 2023-11-29 23:40 UTC
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I was thinking that having a system for game franchises / IPs with also their own fan base and expectations based on this franchise, and is different than a new or different IP. This could also add alternatives such as creating spin-offs and not just sequels.

**Describe alternatives you've considered**
A consolidated IP with a long time on the market could have more fans and people willing to buy a certain game. Some franchises could create hype over time without the need to make an announcement because the public expects a new game. This could give the opportunity to roleplay a little more and allow the creation of spin-offs of certain IPs, this could be used to change the genres in a more credible way or simply give more immersion in different ways.

Additionally, I suggest one last thing to complement this idea: IP / Franchise family tree to view all deliveries of a certain IP and its franchises in a more visual way.

**Additional context**
- When creating a new game, a new IP is created. The name of this could be based on the name of this first game (Could it be modifiable perhaps? ).
- With the franchise family tree you can visually see the chronology of the franchise showing all the games connected in the form of a tree, in the main branch obviously the main games and on the sides the spin-offs or so.
- Some IPs could be very loved and expected so they could spontaneously generate hype after a few years without releasing a game of this IP.
- Certain studies could have more affinity to certain IPs since they are the authors or those who have developed the most games from this IP.
- Additional idea: Lend IPs to other companies to develop games and you earn a percentage or a fixed cost. Or borrow an IP and also pay a percentage or a fixed cost BUT if this IP has many fans and you  make a good game your company can gain many fans.

These are some ideas, it would be great if they could be implemented. I hope I'm not too ambitious.

**Comment by xsellier** [comment] 2023-11-30 08:56
Thank you for the suggestion, I'm closing it since it is a duplicate of #789 while I'm not deleting it in order to keep it as reference.

**Closed as completed by xsellier** 2023-11-30 08:56 UTC
Labels: Duplicate
