### ISSUE TITLE
Suggestion: Game Editions (Rework)

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#773] opened 2022-03-16 17:49 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Can launch a Definitive/Legendary/Special/Standard Edition for a Game

**Describe alternatives you've considered**
Can Launch a Definitive and Standard Edition

**Additional context**
A Definitive/Legendary/Special Edition does not have the same price of the Standard Edition, you can choose the price of the Definitive Or/And Legendary/Special edition, you can also choose if you launch a Definitive/Legendary or Special Edition

**Comment by xsellier** [comment] 2022-08-14 08:39
Duplicate of #363
Closing

**Closed as completed by xsellier** 2022-08-14 08:39 UTC
Labels: Duplicate
