### ISSUE TITLE
Bug / Image [Rus Edition]

### ISSUE THREAD

**Issue by Fozehor** [binogure-studio/city-game-studio-i18n#289] opened 2019-10-11 15:45 UTC
**1** - [Click №1](https://imgur.com/a/mauRfz3) | ---> Image [**Lower down** / **Higher up**]
**2** - [Click №2](https://imgur.com/a/9RSyp5G) | ---> Image [**The font is smaller**]
**3** - [Click №3](https://imgur.com/a/35mezo4) | ---> Image [**Half a word is gone**]
**4** - [Click №4](https://imgur.com/a/DtAt9ZQ) | ---> Image [**Small place**]
**5** - [Click №5](https://imgur.com/a/Z1oPjNz) | ---> Image [**Right and Left**]

**Comment by Fozehor** [comment] 2019-10-11 19:09
### + BUG / Image
**6** - [Click №6](https://imgur.com/a/ySDIivd) | ---> Image [**Text <->**]
**7** - [Click №7](https://imgur.com/a/soIxFva) | ---> Image [**Text <->**]

**Comment by Fozehor** [comment] 2019-10-12 20:38
### + BUG / Image
**8** - [Click №8](https://imgur.com/a/hJC5nU6) | ---> Image [**Text <->**]
**9** - [Click №9](https://imgur.com/a/Sclx255) | ---> Image [**Text <->**]
**9.1** - [Click №9.1](https://imgur.com/a/zf3d2GT) | ---> Image [**Text <->**]
**10** - [Click №10](https://imgur.com/a/ENAxKb2) | ---> Image [**The margins are out of bounds**]
**11** - [Click №11](https://imgur.com/a/Gxts13G) | ---> Image [**Magazine Text <-->**]
**12** - [Click №12](https://imgur.com/a/3qdZbcC) | ---> Image [**The text slid down**]

**Comment by xsellier** [comment] 2019-10-13 22:33
**1** - It is by design, not a bug
**2** - Fixed **v0.26.0-rc7**
**3** - Fixed
**4** - Fixed
**5** - Fixed **v0.26.0-rc7**
**6** - Fixed **v0.26.0-rc7**
**7** - Fixed **v0.26.0-rc7**
**8** - Fixed **v0.26.0-rc7**
**9** - Fixed **v0.26.0-rc7**
**10** - Fixed
**11** - Fixed **v0.26.0-rc7**
**12** - It is by design, not a bug

**Comment by xsellier** [comment] 2019-10-19 14:02
Im gonna close this. Thank you @Fozehor :)

**Closed as completed by xsellier** 2019-10-19 14:02 UTC
Labels: Bug
