### ISSUE TITLE
Suggestion: Stocks 

### ISSUE THREAD

**Issue by dizikkk** [binogure-studio/city-game-studio-i18n#576] opened 2021-04-04 12:45 UTC
**idea of a new feature in the game**
Studios can be bought in the game. But what if we add the ability to buy and sell stocks of companies? And also place shares of your company on the stock market.
Implementation example: https://store.steampowered.com/app/606800/Startup_Company/

**Comment by xsellier** [comment] 2021-04-17 12:12
Duplicate of:
https://github.com/binogure-studio/city-game-studio-i18n/issues/77

**Closed as completed by xsellier** 2021-04-17 12:12 UTC
Labels: Duplicate
