### ISSUE TITLE
Suggestion: Bugs and updates!

### ISSUE THREAD

**Issue by JRC86** [binogure-studio/city-game-studio-i18n#364] opened 2020-02-01 17:22 UTC
Introduce bugs and updates. This can add a new sequence to the end of the development.
You can have an optional playtest at the end of the development where you hunt down bugs.
This can also improve staff mechanic, they might introduce bugs during development that can either be found and fixed at the end or after release with patches.

**Comment by xsellier** [comment] 2020-02-01 17:56
It is a duplicate of this issue: https://github.com/binogure-studio/city-game-studio-i18n/issues/148

And it is implemented in v0.29.0 (not yet released, Im still working on it).

**Closed as completed** 2020-02-01 17:56 UTC
