### ISSUE TITLE
Suggestions/bugs: List of bugs/improvement

### ISSUE THREAD

**Issue by Redxpert** [binogure-studio/city-game-studio-i18n#440] opened 2020-07-18 00:13 UTC
I find little bugs and other improvements but they are so little so i decide to do a list
**Important note:** the **version** that I located that bugs is the **0.31.0 rc-9**
Not important note: I used paint because is more easy to do drawings abobe the screenshots :D
............
**BUGS**
············

Fps with vsync are fixed to 60 fps even if you has an 120hz or 144hz etc screen
--------------------------
When you pause the game, the notifications continue disappearing
--------------------------
When you create a microtransacction in a game it didn’t shows you if it’s enabled or not
(Later I created another game and it left me to scroll down so idk if it's an rare bug or wtf)
--------------------------
![Microtransactions](https://user-images.githubusercontent.com/68289295/87860944-e2011380-c941-11ea-93e4-2e08592d117e.png)
--------------------------
In the firs’t office (your home) in the description puts more meters than it really has
--------------------------
The % of use of consoles and pcs are the same. 
--------------------------
(and isn't very real)
![8e2045c73910e29e48afac8c940b0498](https://user-images.githubusercontent.com/68289295/87862036-14177300-c94c-11ea-8e26-dc30e409acac.png)
![2249e19eabe3a2f35158d3952c6ddba9](https://user-images.githubusercontent.com/68289295/87862059-3c06d680-c94c-11ea-8310-54ef4372b369.png)
--------------------------
when you bought another company you can't use their employees to you're games and if you try to sell the studios to get the workers they will disapear and when I try to contract new emploeyees they simplity dissapear
--------------------------
you can put an object behind another pressing shift (mayus) and if you put its very close to each other the both will be red until you reload the game (only sometimes, other times continue being red)
--------------------------
![coffee](https://user-images.githubusercontent.com/68289295/87861651-7f5f4600-c948-11ea-8dfb-ef1a6982a9a3.png)
--------------------------
![redcofee](https://user-images.githubusercontent.com/68289295/87861166-e8908a80-c943-11ea-9d2e-95c11fd70bcf.png)
--------------------------
You can put 20000 coffees machines and 20000 printers to have the better workers without limitations
--------------------------
![lulaso](https://user-images.githubusercontent.com/68289295/87861193-43c27d00-c944-11ea-8a61-79eeb36d6674.png)
![bildin](https://user-images.githubusercontent.com/68289295/87861196-4a50f480-c944-11ea-8d6e-b4a3bf1beed5.png)
--------------------------
The number that represents if my fanbase is going up or down is always in 0
--------------------------
![what second part](https://user-images.githubusercontent.com/68289295/87860907-76b74180-c941-11ea-8207-ab3f0f94b6e5.png)
--------------------------
The number that represents if my money is going up or down didn’t represent the same than the chart
--------------------------
![what](https://user-images.githubusercontent.com/68289295/87860910-7b7bf580-c941-11ea-9ddb-f6442faa74a1.png)
--------------------------
with the game in fullscreen you can’t press the windows key to show the searcher, and also if you press the “impr pant” to print a screenshot, the game won't let you do it.
--------------------------
If your fan base is too big you won't be able to see the difference between months
--------------------------
![no diference](https://user-images.githubusercontent.com/68289295/87863804-b856e500-c95f-11ea-8d60-64970407fbe8.png)
--------------------------
The money that you spend when creating an update isn't subtracted at the total profit of the game
--------------------------
...............................................
**LITTLE IMPROVEMENTS**
···············································
--------------------------
In the detailed chart of every game there is not number of players by monthly
--------------------------
![4b7c0816a5a37654c092e859a93227e7](https://user-images.githubusercontent.com/68289295/87862155-555c5280-c94d-11ea-9428-5c582fecd022.png)
--------------------------
In the charts of every videogame, you can’t see the number of games sold or downloads if free by monthly. I think that can be with the chart of the fan base
--------------------------
![charts](https://user-images.githubusercontent.com/68289295/87860894-61daae00-c941-11ea-9b4c-00a9220ca634.png)

(The same to the graphics of the digital store)

![charts2](https://user-images.githubusercontent.com/68289295/87860900-67d08f00-c941-11ea-85a9-e8f61cddc6f1.png)

--------------------------
Possibility to change the type of coin between € / $ / £ etc
--------------------------
When you auto fill an office with servers the game do the same that will do a person who never play tetris, so you will lost a lot of space between servers.
--------------------------
![0432d937bb78c52188b4814371bcb5c8](https://user-images.githubusercontent.com/68289295/87861722-4a9fbe80-c949-11ea-8506-f5eace877707.png)
--------------------------
When you are viewing graphs of whatever you are you cannot go to past data
--------------------------
![getback bruh](https://user-images.githubusercontent.com/68289295/87862218-f77c3a80-c94d-11ea-82c2-a65aed83b8a5.png)
--------------------------
Why the maximum cost of microtransactions is 30 € / $ , we want more money to steal our players 
--------------------------
A way to investigate about an platform or an phase of development that cost too much but you don't need to create more games
--------------------------
It's complicated to manage with a human resources person a very big studio
--------------------------
A button to repare the coffee machines or other broken things instantly in the mail
--------------------------
An action to pause a game development 4 example, if you want to develop an update without cancelling the game
--------------------------
You can't exit of the game whitout saving, so you can't reload game after ruining you.
--------------------------
.
I hope I've helped you
If anyone find more little bugs or other improvements, you can put it in the comments not to fill the bugfix page
.

**Comment by xsellier** [comment] 2020-07-19 18:17
> Fps with vsync are fixed to 60 fps even if you has an 120hz or 144hz etc screen

**Won't fix** - This is a game engine limitation, I cannot fix it.

> When you pause the game, the notifications continue disappearing

**TODO** Nice one.

> When you create a microtransacction in a game it didn’t shows you if it’s enabled or not (Later I created another game and it left me to scroll down so idk if it's an rare bug or wtf)

**TODO** - If its enabled there is a price just beside it, otherwise there is no price. But I can make it more readble for sure!

> In the firs’t office (your home) in the description puts more meters than it really has

**Won't fix** - Studio size is defined by block. Meaning you cannot see a difference between a 80m² and a 82m². But you will notice a difference between a 50m² and a 60m².

> The % of use of consoles and pcs are the same.

**Won't fix** - It is based on real data, I mean I gathered real data from wiki/google...

> When you bought another company you can't use their employees to you're games and if you try to sell the studios to get the workers they will disapear and when I try to contract new emploeyees they simplity dissapear

**Won't fix** - In fact, those employees are not assigne dto the studio. You will have toassign them manually (or automatically via the menu button). But if you are playing in Insane/hard, then all non=assigned employees are going to leave your company.

> you can put an object behind another pressing shift (mayus) and if you put its very close to each other the both will be red until you reload the game (only sometimes, other times continue being red)

**TODO** Nice one, I tested this feature deeply, but never got that issue yet.

> You can put 20000 coffees machines and 20000 printers to have the better workers without limitations

**TODO** - Yes you can do that, and it is normal. Because it is way better to have 6 employees in a studio than 1 employee with 20 coffee machine. But I can add a limitation for sure.

> The number that represents if my fanbase is going up or down is always in 0

**TODO** - This number shows the diffs between the last month and the current month. Im gonna check if there is a bug anyway.

> The number that represents if my money is going up or down didn’t represent the same than the chart

**TODO** - Those are the expenses of the last action. So for sure it does not match. Im gonna check if there is a bug anyway.

> with the game in fullscreen you can’t press the windows key to show the searcher, and also if you press the “impr pant” to print a screenshot, the game won't let you do it.

**Need more info** - May you share a screenshot please.

> If your fan base is too big you won't be able to see the difference between months

**TODO** - Nice one. Easy to fix

> The money that you spend when creating an update isn't subtracted at the total profit of the game

**TODO** - Nice one.

> In the detailed chart of every game there is not number of players by monthly

**Won't fix** - Number of returning players is the number of usual players

> In the charts of every videogame, you can’t see the number of games sold or downloads if free by monthly. I think that can be with the chart of the fan base

**TODO** - Indeed, that data can be added.

> Possibility to change the type of coin between € / $ / £ etc

**TODO** - Yup, why not

> When you auto fill an office with servers the game do the same that will do a person who never play tetris, so you will lost a lot of space between servers.

**Won't fix** - Indeed, it is not optimized. It is done that way on purpose, because people who want to micro-manage their company can do it the way they want it. However, you should be able to add new pattern to furnish your studios via the mod support.

> When you are viewing graphs of whatever you are you cannot go to past data

**TODO** - That is normal, the game keep only the last 12 months. Before adding more data to the savegame, I need to compress the savegame, otherwise the savegame might weight something like 100Mb, and since Im using the Steam Cloud to synchronize the saves, there is a limitation in place.

> Why the maximum cost of microtransactions is 30 € / $ , we want more money to steal our players

**TODO** - Im gonna change it for a bigger number (1000 $).

> A way to investigate about an platform or an phase of development that cost too much but you don't need to create more games

**Please split** - For that feature request, Im gonna ask you to create a separated ticket.

> It's complicated to manage with a human resources person a very big studio

**Please split** - I agree, and so far I haven't found a better way, but I haven't really tried (sorry).

> A button to repare the coffee machines or other broken things instantly in the mail

**TODO** - There is a button on the bottom men, if you click it, it is going to fix all the broken stuff

> An action to pause a game development 4 example, if you want to develop an update without cancelling the game

**Duplicated** - Duplicate of this ticket: https://github.com/binogure-studio/city-game-studio-i18n/issues/229

> You can't exit of the game whitout saving, so you can't reload game after ruining you.

**Won't fix** - It is done on purpose. But youcan always copypaste the current savegame before closing the game.

Thank you, for all those suggestions/bug reports. You help me a lot by submitting this ticket!

**Comment by Redxpert** [comment] 2020-07-19 18:45
**First of all:**
If i found more little bugs or something similar, I create another issue, or just comment it here?

--------------------
Fps with vsync are fixed to 60 fps even if you has an 120hz or 144hz etc screen
--------------------

> Won't fix - This is a game engine limitation, I cannot fix it.

- Try to enable the "Vsync Via Compositor in Godot plz, then I'll tell you if it's working on 144hz or not 
(Window configuration)

If you have any problem with that look at here -> https://github.com/godotengine/godot/issues/35996
Or disable it, isn't a problem

--------------------
with the game in fullscreen you can’t press the windows key to show the searcher, and also if you press the “impr pant” to print a screenshot, the game won't let you do it.
--------------------

> **Need more info** - May you share a screenshot please.


- I don't know how to represent thet bug in a screenshot.
For the next rc update, can you try to put the fullscreen mode to borderless?
(window settings another time xD)


--------------------
In the firs’t office (your home) in the description puts more meters than it really has
--------------------

> Won't fix - Studio size is defined by block. Meaning you cannot see a difference between a 80m² and a 82m². But you will notice a difference between a 50m² and a 60m².

- I mean that in the first office (you're home) they puts that it has more metters than it really has (you can only put 4 tables but it say that has 120m2 or more)

![toobig](https://user-images.githubusercontent.com/68289295/87885183-396fb400-ca14-11ea-8fde-c1e707369d34.png)

--------------------
When you are viewing graphs of whatever you are you cannot go to past data
--------------------

> TODO - That is normal, the game keep only the last 12 months. Before adding more data to the savegame, I need to compress the savegame, otherwise the savegame might weight something like 100Mb, and since Im using the Steam Cloud to synchronize the saves, there is a limitation in place.

- Lol idk that the graphs occoups too much, i think that it's only nodes with X and Y position.
Oki 

--------------------
A button to repare the coffee machines or other broken things instantly in the mail
--------------------

> TODO - There is a button on the bottom men, if you click it, it is going to fix all the broken stuff

- Oh sorry, I have not seen it xD

--------------------
A way to investigate about an platform or an phase of development that cost too much but you don't need to create more games
--------------------

> **Please split** - For that feature request, Im gonna ask you to create a separated ticket.

- Oki ->#442

--------------------
It's complicated to manage with a human resources person a very big studio
--------------------

> **Please split** - I agree, and so far I haven't found a better way, but I haven't really tried (sorry).

Idea 1: Instead of handling all people 1 by 1 you can do by little  groups of 5 for example

Idea 2: You can create a table
![Table](https://user-images.githubusercontent.com/68289295/87882496-8c3f7080-ca00-11ea-8530-e98481cc63ea.png)

--------------------
The money that you spend when creating an update isn't subtracted at the total profit of the game
--------------------

> TODO - Nice one.

I have thought that you can add that cost to the data of marketing cost of the game

--------------------
..........................................
Other improvements
..........................................
--------------------
--------------------
You can't change the company name after creating it
--------------------

- So if you called you're company  "potato games" and after the years it stopped liking you, you will need to create another game.
I think that it will good to change the company game but that also affects negatively to the fans 4 example, going down an 10%
--------------------
It's too easy to buy all the others companies (In 2030 the most expensive cost 9G aprox) and with a good game you can get 90G or more (I don't know if that has any relation with the game dificulty because that happend to me in Normal)
--------------------

- The details when you pass the cursor below the game are a little bit molest when you're scrolling down because they are very big

- I think that this stats could go with the financial details, or only being showed when you put the cursor on the 3 lines, and not in all the graphic and name.

![toobig2](https://user-images.githubusercontent.com/68289295/87889233-de988580-ca30-11ea-9f3a-a72916c42790.png)
![data](https://user-images.githubusercontent.com/68289295/87889271-14d60500-ca31-11ea-86e9-86dc993458d9.png)

--------------------
*BUG
The anisotropic filter isn't working (I have rounded the places where it shows the most)
If you need, download the image and do zoom on it
Important Info: I'm using vulcan api
--------------------

![NoAntialiasing](https://user-images.githubusercontent.com/68289295/87889771-94fd6a00-ca33-11ea-9eb4-fcd27f0d4707.png)

-I think that these forums will help you:

https://www.reddit.com/r/godot/comments/3wajkq/anti_aliasing/
https://www.reddit.com/r/godot/comments/gu7aep/antialiasing_questions/
https://gamedev.stackexchange.com/questions/166616/godot-what-options-are-there-for-removing-the-filtering-or-anti-aliasing-from-t

--------------------
What is the use for this white bar?
![whatistis](https://user-images.githubusercontent.com/68289295/87890766-1c4cdc80-ca38-11ea-8854-e23e3e2e5979.png)
--------------------

I hope I've helped you another time :D

**Comment by xsellier** [comment] 2020-07-20 07:22
> If you have any problem with that look at here -> godotengine/godot#35996
> Or disable it, isn't a problem

Im not using v3.2, but v2.1. And disabling vsync in 2.1 is a terrible idea.

> For the next rc update, can you try to put the fullscreen mode to borderless?
> (window settings another time xD)

This feature is not working properly in 2.1, so I cannot enable it.

> I mean that in the first office (you're home) they puts that it has more metters than it really has (you can only put 4 tables but it say that has 120m2 or more)

Indeed

> Lol idk that the graphs occoups too much, i think that it's only nodes with X and Y position.
> Oki

Every single data has to be stored in the savegame. That is my point.

> Other improvements

Please create a ticket per suggestion. I won't be able to keep this ticket open forever.

> The anisotropic filter isn't working (I have rounded the places where it shows the most)
> If you need, download the image and do zoom on it
> Important Info: I'm using vulcan api

This is a limitation of the 2.1, plus it uses OpenGL 2,0, you cannot use the Vulkan API.

> What is the use for this white bar?

Notification bar.

**Comment by Redxpert** [comment] 2020-07-20 09:34
Oki, i haven't more ideas or finded bugs so i close it.

**Comment by xsellier** [comment] 2020-07-20 11:58
Sorry but I need this ticket to remain open untill I fix all the bugs found

**Comment by Redxpert** [comment] 2020-07-20 12:14
ohh, sorry     
Idk how to use github well yet
#430 this is a good idea to repair the 20000 coffee machines and printers

**Comment by xsellier** [comment] 2022-08-06 09:34
UIt's a bit late, ut most of the reports you've have been fixed.
- Furnishing studios has changed quite a lot
- There's an upper limit for happiness/productivity boosts
- You can investigate platforms, genres thanks to marketing managers
- Micro-transactions threshold has been increased
- An auto-repair coffee-machines have been added
- You can disable auto-save
- You can pause a game development
- First office description has been fixed (it's 20 m² now)
- Update costs added to game costs
- You can change the company name
- It's way harder to buy out competitors (plus they can buy each others now)

But, others cannot be fixed, even if I improved the rendering there's no AA/MSAA in Godot v2.1 for example.

Thank you for this helpful feedback, closing it now.

**Closed as completed by xsellier** 2022-08-06 09:34 UTC
Labels: enhancement

**Comment by GianluPlay** [comment] 2022-08-06 15:26
Sugerencia mas larga que carretera china ekisde
