### ISSUE TITLE
Suggestion: Some QoL/suggestions

### ISSUE THREAD

**Issue by Patyfatycake** [binogure-studio/city-game-studio-i18n#188] opened 2019-04-19 03:52 UTC
### QOL
- When assigning employee then unassigned employee's are first.

- HR (or something) which can search for good employees and steal them from other companies/Find/filter criteria when hiring and prompt you or hire when they are met
- When porting multiplayer games have it default to a console which supports it if possible.

### Content
- Hr Could also help with happiness etc or prompt you when someone is unhappy
- Training courses
- Agile coach/Manager etc - Which will help with sending employees to sleep to prepare for their sections
- Hosting tournaments for your game for publicity

**Comment by xsellier** [comment] 2019-04-19 15:16
Thank you for those suggestions, those are really good.
About the first one, you can click on the column name to sort the staff, however it is now sorted by studio by default now:
![image](https://user-images.githubusercontent.com/6616005/56430448-60c95580-6294-11e9-9faa-e584e578a147.png)

For the HR feature, it is on the roadmap already, it is going the next big feature (https://github.com/binogure-studio/city-game-studio-i18n/projects/1#card-17761184).

I wanted contracts to act as training courses, but adding a training course is easy to do, so I will add a separate feature for that indeed.

About Hosting tournament, I will keep that idea in mind!

**Comment by xsellier** [comment] 2019-12-07 18:01
QOL: Already implemented in v0.27.5
Suggestions:
1. HR alreay helps with happiness, however I'm not sure you want to be bothered by your HR in order to _micro-manage_ your dev team. So, I'm not gonna implement this one.
2. Training course: Duplicate of https://github.com/binogure-studio/city-game-studio-i18n/issues/214
3. Producers are here for that. Plus HR helps you manage your staff schedules. So, adding an agile coach won't bring anything to the game
4. Duplicate of https://github.com/binogure-studio/city-game-studio-i18n/issues/319

Since all the points have been covered and most of them have been implemented Im closing this ticket

**Closed as completed by xsellier** 2019-12-07 18:01 UTC
Labels: enhancement
