### ISSUE TITLE
Suggestion: The 3 ideas

### ISSUE THREAD

**Issue by StormyHauk** [binogure-studio/city-game-studio-i18n#259] opened 2019-09-01 08:29 UTC
I still have many ideas for the future of the game and i still want to say thank you for improving the game and that you made it in the first place.

1. This one may sound weird, but what if we could have like 2 themes. For example if you wanted to make a horror pirate game that is a interactive movie. This may be too complicated, but idk since i dont make games

2. I would like to make offers or get offers to get someone to make a tv series, book series or movies about a game series that i own and if the first season, book or movie was succesful they make more. If you dont want anyone to do it for you and sharing money with them you could buil your own studio for movies and tv series.

3. I think that switch is missing in the game, but it can be that i just havent noticed it.

I think maybe that nr 2 will go to far into movie making so that may not be a good idea, but thanks for making this wonderful game and have a good day

**Comment by xsellier** [comment] 2019-12-07 18:09
1. ~~Combinating 2 themes is really easy to do, but, it will also add more complexity to the UI. And I'm not sure it is worth it. I mean, Custom games engines are going to be available with v0.28.0, and I'm sure this feature request won't be needed anymore.~~ Duplicate of https://github.com/binogure-studio/city-game-studio-i18n/issues/151
2. Duplicate of: https://github.com/binogure-studio/city-game-studio-i18n/issues/97
3. Platform is present (reworked its visual so you can recognize it)

**Comment by xsellier** [comment] 2020-03-04 17:25
I close this one and keep the other tickets open:
- https://github.com/binogure-studio/city-game-studio-i18n/issues/151
- https://github.com/binogure-studio/city-game-studio-i18n/issues/97

**Closed as completed by xsellier** 2020-03-04 17:25 UTC
Labels: Duplicate
