### ISSUE TITLE
Suggestion: Fans

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#724] opened 2021-11-05 01:32 UTC
Can put fans in the desktops of the employees, has monthly cost like the Coffe Machine
Benefits: More happiness, More productivity

**Comment by xsellier** [comment] 2021-11-05 07:44
Duplicate of https://github.com/binogure-studio/city-game-studio-i18n/issues/96

**Closed as completed by xsellier** 2021-11-05 07:44 UTC
Labels: Duplicate
