### ISSUE TITLE
Suggestion: Microtransaction's and loot boxes 

### ISSUE THREAD

**Issue by BIGEYES92** [binogure-studio/city-game-studio-i18n#143] opened 2019-03-21 18:14 UTC
Being able to add micro transactions and loot boxes to games And deciding if they are cosmetics or pay to win, You could control the loot box percentage too. This could be great also if the competitors are being very greedy and Putting all of this stuff in their new games, and you could become the only developer the fans trust by making games, that don't give in to these greedy tactics, and maybe fans will start boycotting these greedy game developers and eventually they try not being greedy. Just a thought but it would be fun to play out

**Comment by xsellier** [comment] 2020-03-14 13:00
Sorry for the late response.
This is a duplicate of this ticket https://github.com/binogure-studio/city-game-studio-i18n/issues/384
This feature will be implemented in v0.30.0

**Closed as completed by xsellier** 2020-03-14 13:00 UTC
Labels: Duplicate, enhancement
