### ISSUE TITLE
Suggestion: Countries Update (Alternative 1)

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#756] opened 2022-02-18 00:32 UTC
Can build Studios in different countries, also in hard difficult every country has different taxes (taxes are applied to games  and stocks)

**Comment by xsellier** [comment] 2022-02-18 08:46
Looks like a duplicate of: https://github.com/binogure-studio/city-game-studio-i18n/issues/735
Closing

**Closed as completed by xsellier** 2022-02-18 08:46 UTC
Labels: Duplicate
