### ISSUE TITLE
Suggestion: Studios become Offshoots

### ISSUE THREAD

**Issue by JohnMann87** [binogure-studio/city-game-studio-i18n#98] opened 2019-03-03 10:01 UTC
I mean its a pretty out there idea, but if you have a big studio which is your main then theres no point in having multiple. so there could be an option that makes the unused office and workers, to become a puppet studio. They make games equal to the amount of people so 1-2 make indie games 3 to 5 make normal games and so on. so its another way to make money. of course it'd be a percentage based thing the smaller the people the higher the percentage. 

It also make the game more unique as no other game dev games that i know of let the players do that

**Comment by xsellier** [comment] 2019-03-04 17:41
In fact, I want to add a producer role. It will help you manage other studios (acting as puppets)

**Comment by xsellier** [comment] 2021-09-05 08:25
Duplicate of this ticket:
https://github.com/binogure-studio/city-game-studio-i18n/issues/409

**Closed as completed by xsellier** 2021-09-05 08:25 UTC
Labels: enhancement
