### ISSUE TITLE
Suggestion: Acquire IPs

### ISSUE THREAD

**Issue by Saputo228** [binogure-studio/city-game-studio-i18n#461] opened 2020-08-18 18:18 UTC
When you buy a company can you make it so you acquire there IPs as well?

Doing this would allow you to get game of year games, if they won the title, and also be able to keep making there games they already made.

Or allow companies to buy and sell there IP's to other companies.

I also would suggest tossing some small indie companies in the mix as well, during the mid-2000s that can be bought as well.

**Comment by xsellier** [comment] 2020-08-18 18:27
Duplicate of https://github.com/binogure-studio/city-game-studio-i18n/issues/97

**Closed as completed by xsellier** 2020-08-18 18:27 UTC
Labels: Duplicate
