### ISSUE TITLE
Suggestion: More in depth research

### ISSUE THREAD

**Issue by WayneFTWGitHUB** [binogure-studio/city-game-studio-i18n#268] opened 2019-09-19 20:31 UTC
I think the research in this game is good but it could be better. If you could for an example research something so you could make your own console, research a green screen that you can have in your studio and stuff like that.

**Comment by xsellier** [comment] 2019-09-21 16:01
About making your own console, there is already a ticket for that one:
https://github.com/binogure-studio/city-game-studio-i18n/issues/226

Anyway I get your idea. Having some point to spend on research, but not only for new Game Genre, it is something Im gonna implement. Have a look at those tickets:
https://github.com/binogure-studio/city-game-studio-i18n/issues/261
https://github.com/binogure-studio/city-game-studio-i18n/issues/194
https://github.com/binogure-studio/city-game-studio-i18n/issues/260

I'm closing this ticket because it is a duplicate of those other issues

**Closed as completed by xsellier** 2019-09-21 16:01 UTC
Labels: Duplicate
