### ISSUE TITLE
Suggestion: Console Features

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#762] opened 2022-02-26 20:52 UTC
Suggestion: Add console features

Cost: 5K - 1 Mil per Feature

Cost (Development and Design Points): 15 - 5000 per feature

Short List Of Console Features: Online Games, Backward Compatibility, 2 Controller Support, 3 Controller Support, 4 Controller Support, 8 Controller Support, Reset Button, User Profiles, Friends, Crossplay, External HDDs/SSDs Support, Achievments, Bluetooth Support

Console Features can be added and edited by mods and doesnt need an image

**Comment by xsellier** [comment] 2022-02-27 11:00
Hey,

I woder, what's a Console Feature? Is it a game engine feature?

**Comment by GianluPlay** [comment] 2022-02-27 15:55
> Hey,
> 
> I woder, what's a Console Feature? Is it a game engine feature?

Its an Engine Feature but for consoles

**Comment by xsellier** [comment] 2022-02-27 15:58
* Does this feature request related to a specific problem?
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
* Please describe all the alternatives you've considered for that specific problem.

**Comment by xsellier** [comment] 2022-06-28 08:10
Since this issue doesn't fit the issue template, nor explains how or why it enhance the gameplay, I'm closing it.

**Closed as completed by xsellier** 2022-06-28 08:11 UTC
Labels: Incomplete
