### ISSUE TITLE
Suggestion: A way to investigate about an platform or genre

### ISSUE THREAD

**Issue by Redxpert** [binogure-studio/city-game-studio-i18n#442] opened 2020-07-19 19:14 UTC
If you want to know more about 4 example, the % of any genre you will need to do a loooot of games
So, like in mad games tycoon, i think that a form to investigate about a genre will be good

4 example, you could investigate about the adventure genre and spend a lot of money doing that to do better the games
or investigate what genre is better for a platform than other without need to make a lot of games.

(Like an R&D department)

**Comment by xsellier** [comment] 2020-07-20 07:44
You can either make games, or make contracts. If you make contracts you are going to learn alot about genre.
Sorry but this has already been suggested.

Duplicate of: https://github.com/binogure-studio/city-game-studio-i18n/issues/261

**Closed as completed by xsellier** 2020-07-20 07:44 UTC
Labels: Duplicate
