### ISSUE TITLE
Suggestion: Release Button and Market

### ISSUE THREAD

**Issue by Saputo228** [binogure-studio/city-game-studio-i18n#459] opened 2020-08-13 01:37 UTC
**Is your feature request related to a problem? Please describe.**
Are you able to add a Release Button and also allow people to Market there Expansions to MMO's?

Also, can you add Buying IP's from other companies?

Doing this would help bring back old fans and also maybe help reboot old MMO's

Like if you bought an IP from a Company and Remastered it as a new release this would be a really good idea and would help keep companies that want to keep MMO's Paid and Free as there only games, I have a play through going like that and it is great and a lot of fun, I started out with Just free to play, and over a few years went to pay to play, and I just made a game that is a score of 99 and is bringing me in Trillions, but sadly I did not get the game of a year :(

I enjoy playing this way because it is a lot harder to play and make it in the biz.
Thank you again.

**Comment by xsellier** [comment] 2020-08-18 18:28
Duplicate of:
- https://github.com/binogure-studio/city-game-studio-i18n/issues/97
- https://github.com/binogure-studio/city-game-studio-i18n/issues/399
- https://github.com/binogure-studio/city-game-studio-i18n/issues/351

**Closed as completed by xsellier** 2020-08-18 18:28 UTC
Labels: Duplicate
