### ISSUE TITLE
Suggestion: Country system

### ISSUE THREAD

**Issue by GianluPlay** [binogure-studio/city-game-studio-i18n#728] opened 2021-11-05 01:55 UTC
Country system, i dont know how to detail this but, one like the Mad Games Tycoon 2 System

**Comment by xsellier** [comment] 2021-11-05 07:42
Duplicate of: https://github.com/binogure-studio/city-game-studio-i18n/issues/547

**Closed as completed by xsellier** 2021-11-05 07:42 UTC
Labels: Duplicate, Incomplete
