### ISSUE TITLE
Suggestion: Copy/paste your furniture (better mode)

### ISSUE THREAD

**Issue by bigbangnet** [binogure-studio/city-game-studio-i18n#456] opened 2020-08-07 03:49 UTC
**Is your feature request related to a problem?
You could use the auto-furniture mode for servers or even the desk but....its not "efficient" enough. 

**Describe the solution you'd like**
For example, the servers, I'd like to place servers as close together as I can. To do that, I can press shift but its very long with you have the maximum floor size.... very long time to do. How about some editing features as in you click on your mouse to place your server and drag the mouse to "copy" it on the floor. The motion would use the maximum space on the floor.

That way, when you place furniture it should be a lot faster. Click and drag to place 6 desk in one mouse movement instead of clicking, placing on the right spot then do that 5 other times.

**Describe alternatives you've considered**
None, you have to click, click click your way until you're happy with the results.

**Comment by xsellier** [comment] 2020-08-10 08:52
Closing, duplicate of:
https://github.com/binogure-studio/city-game-studio-i18n/issues/231

**Closed as completed by xsellier** 2020-08-10 08:52 UTC
